---
title: "mlr3learners.lgbpy - Multiclass Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mlr3learners_lightgbm}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mlr3learners.lgbpy)
library(mlr3)
library(paradox)
library(mlbench)
```

# Create Autotuner to find best num_iter

```{r eval=FALSE}
learner$param_set$values <- list("num_threads" = 1L)
resampling <- mlr3::rsmp(.key = "cv", folds = 5L)
print(resampling)

measures <- mlr3::msr("classif.logloss")

tune_ps <- ParamSet$new(
  list(
  ParamInt$new(
    id = "num_leaves",
    lower = 6L,
    upper = 60L
  )
))

terminator <- mlr3tuning::term("stagnation", iters = 50)

tuner <- mlr3tuning::tnr("random_search")

at <- mlr3tuning::AutoTuner$new(
  learner = learner,
  resampling = resampling,
  measures = measures,
  tune_ps = tune_ps,
  terminator = terminator,
  tuner = tuner
)
```
